### ISSUE TITLE
Using Kernel Driver .SYS

### ISSUE THREAD

**Issue by isvktt** [3a1/CS2-Calypso#9]
I think it would be interesting to create a .sys driver for people who don't have a motherboard that supports SHELL, putting an option in the config where the user can choose to use the EFI driver or the .sys driver or something like that, it would be interesting and would achieve more people, congratulations on the project

**Comment by 3a1** [comment]
Thanks very much, about .sys driver I thought about to add other modes such as simple external and also a .sys driver usage. But problem is that its cause little misunderstandings from initials goals of this project. Starting assumptions of this project for me is try to make a CS2 cheat with Arduino support that will work via EFI Driver. So this project is from start more like experimental and specific and not trying to aim for works with all pc's. So if I will have an idea to create a .sys driver cheat for me it's better to create a new project that will use .sys driver than try to combine that in cheat which is made to work with EFI.

**Comment by isvktt** [comment]
I understand your point of view, I think it would deviate a little from the real purpose of this project, I think it would be good to launch another project with a different name, using the .sys driver with the Arduino inputs, thanks for the answer!
